server:
  port: 8084

spring:
  application:
    name: notification-service

  cloud:
    stream:
      bindings:
        transactionEventConsumer-in-0:
          destination: transaction-events
          group: notification-group
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
