spring:
  application:
    name: transaction-service

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092       # your Kafka broker
          autoCreateTopics: true        # create topics automatically if missing
      bindings:
        transactionCreatedEvent-out-0:
          destination: transaction-created-topic
          producer:
            retries: 3                  # limit producer retry attempts

    loadbalancer:
      ribbon:
        enabled: false                 # disable Ribbon if not needed
      retry:
        enabled: false                 # prevent infinite retries on load balancer

feign:
  client:
    config:
      default:
        connectTimeout: 5000          # 5 seconds connection timeout
        readTimeout: 5000             # 5 seconds read timeout
        retryer:
          period: 1000                # 1 second between retries
          maxPeriod: 5000             # max wait
          maxAttempts: 3              # max 3 retries

resilience4j:
  retry:
    instances:
      transactionServiceRetry:
        max-attempts: 3               # max retries
        wait-duration: 2s             # wait between retries
